name: Talend JRuby images

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  jruby-92-jre8:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build JRuby 9.2 JRE 8
      uses: docker/build-push-action@v2
      with:
        context: ./talend
        file: ./talend/Dockerfile
        pull: true
        push: true
        tags: |
          full360/talend:9-jre8
          full360/talend:9.2-jre8
